from __future__ import annotations

from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class Ring(Protocol):
    def __add__(self, other: Any) -> Any: ...

    def __sub__(self, other: Any) -> Any: ...

    def __mul__(self, other: Any) -> Any: ...

    def __neg__(self) -> Any: ...

    def __eq__(self, other: Any) -> bool: ...

    def zero(self) -> Any: ...

    def one(self) -> Any: ...

    def norm(self) -> float: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...
